export enum NotificationsFeedEventsEnum {
  CLOSE_NOTIFICATIONS_FEED = 'CLOSE_NOTIFICATIONS_FEED',
  CLEAR_NOTIFICATIONS_FEED_HISTORY = 'CLEAR_NOTIFICATIONS_FEED_HISTORY',
  OPEN_NOTIFICATIONS_FEED = 'OPEN_NOTIFICATIONS_FEED',
  // Event to update the pending transactions list
  PENDING_TRANSACTIONS_UPDATE = 'PENDING_TRANSACTIONS_UPDATE',
  // Event to update the transactions history list
  TRANSACTIONS_HISTORY_UPDATE = 'TRANSACTIONS_HISTORY_UPDATE'
}
