export enum LedgerConnectEventsEnum {
  CONNECT_DEVICE = 'CONNECT_DEVICE',
  ACCESS_WALLET = 'ACCESS_WALLET',
  GO_TO_PAGE = 'GO_TO_PAGE',
  CLOSE = 'CLOSE',
  DATA_UPDATE = 'DATA_UPDATE',
  UI_DISCONNECTED = 'UI_DISCONNECTED'
}
